"""atualiza tabelas

Revision ID: f480509d20e2
Revises: 17a88b2c2919
Create Date: 2025-10-24 14:14:22.566382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f480509d20e2'
down_revision = '17a88b2c2919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrinhos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('carrinhos', schema=None) as batch_op:
        batch_op.drop_column('preco')

    # ### end Alembic commands ###
